name: com.roy93group.flutter_tutorial
description: Flutter Resources Collections.
publish_to: 'none'
version: 2023.10.08+20231007

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ##a
  applovin_max: ^3.9.0
  after_layout: ^1.2.0
  animated_background: ^2.0.0
  animated_bottom_navigation_bar: ^1.3.3
  animated_text_kit: ^4.2.2
  animated_toggle_switch: ^0.7.0 #migrate later
  animations: ^2.0.11
  another_flushbar: ^1.12.30
  avatar_glow: ^3.0.1
  auto_size_text: ^3.0.0
#  auto_route: ^7.8.4
  app_settings: ^5.1.1
  awesome_dialog: ^3.2.0

  ##b
  badges: ^2.0.3 #migrate later
  battery_plus: ^6.0.1
  basic_utils: ^5.7.0
  bottom_bar_with_sheet: ^2.4.0
  bottom_navy_bar: ^6.0.0
  blur: ^3.1.0
  bloc: ^8.1.4

  ##c
  cached_network_image: ^3.3.1
  calendar_appbar: ^0.0.6
  calendar_view: ^1.1.0
  camera: ^0.10.5+9
  carousel_slider: ^4.2.1
  circular_bottom_navigation: ^2.4.0
  chewie: ^1.8.1
  clipboard: ^0.1.3
  colorful_background: ^0.0.4
  confetti: ^0.7.0
  connectivity_plus: ^5.0.2
  convex_bottom_bar: ^3.2.0
  country_picker: ^2.0.25
  clay_containers: ^0.3.4
  characters: ^1.3.0
  circular_reveal_animation: ^2.0.1
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3
  curved_navigation_bar: ^1.0.3
  csslib: ^1.0.0

  ##d
  date_picker_timeline_fixed: ^2.0.0
  dart_rss: ^3.0.1
  d_chart: ^2.6.2
  drag_select_grid_view: ^0.6.2
  device_info_plus: ^9.0.3
  delayed_display: ^2.0.0
  device_preview: ^1.1.0
  diacritic: ^0.1.5
  dio: ^5.4.3+1
  flutter_pretty_dio_logger: ^3.0.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  dots_indicator: ^2.1.0 #migrate later
  draggable_scrollbar: ^0.1.0
  dropdown_button2: ^1.9.4 #migrate later
  drop_shadow: ^0.1.0

  ##e
  easy_debounce: ^2.0.3
#  easy_refresh: ^3.3.2+4
  elastic_drawer: ^2.0.2
  email_validator: ^2.1.17
  encrypt: ^5.0.3
  english_words: ^4.0.0
  event_bus: ^2.0.0
  equatable: ^2.0.5

  ##f
  fast_color_picker: ^0.1.1
  feedback: ^3.0.1
  focus_detector: ^2.0.1
  folding_cell: ^1.0.2
  fk_toggle: ^0.1.4
  font_awesome_flutter: ^10.7.0
#  firebase_core: ^2.28.0
#  firebase_analytics: ^10.10.0
#  firebase_crashlytics: ^3.5.0
#  firebase_remote_config: ^4.4.0
  file_picker: ^5.5.0
  flash: ^3.1.0
  flat_3d_button: ^1.0.3
  fl_chart: ^0.61.0 #migrate later
  flexible_calendar: ^1.0.1
  flex_color_scheme: ^7.3.1
  flex_color_picker: ^3.4.1
  floating_bubbles: ^2.6.2
  flip_card: ^0.7.0
  flutter_animated_button: ^2.0.3
  flutter_bloc: ^8.1.5
  flutter_circle_color_picker: ^0.3.0
  flutter_colorpicker: ^1.0.3
  flutter_credit_card: ^3.0.7
  flutter_displaymode: ^0.6.0
  flutter_drawing_board: ^0.4.4+2
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^6.0.3
  #flutter_html: ^2.2.1
  #  flutter_file_view: ^2.1.2 //bi gg reject vi co download manual apk -> should not use this plugin
  flutter_local_notifications: ^9.9.1 #migrate later
  flutter_linkify: ^6.0.0
  #  flutter_map: ^3.1.0
  flutter_markdown: ^0.6.18+2
  flutter_native_timezone: ^2.0.0
  flutter_native_splash: ^2.4.0
  flutter_offline: ^3.0.1
  flutter_image_compress: ^1.1.3
  flutter_inappwebview: ^6.0.0
  flutter_rating_bar: ^4.0.1
  flutter_reaction_button: ^1.0.8 #migrate later
  flutter_rounded_date_picker: ^3.0.4
  flutter_riverpod: ^2.5.1
  flutter_scalable_ocr: ^2.0.0
  flutter_simple_treeview: ^3.0.2
  flutter_slidable: ^0.6.0 #migrate later
  flutter_slider_drawer: ^2.1.3
  flutter_smart_dialog: ^4.9.5+1
  flutter_snake_navigationbar: ^0.6.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^1.1.6 #migrate later
  flutter_speed_dial: ^7.0.0
  flutter_switch: ^0.3.2
  flutter_spinkit: ^5.2.1
  flutter_sticky_header: ^0.6.5
#  flutter_screen_lock: ^9.0.2
  flutter_phoenix: ^1.1.1
  fluttertoast: ^8.2.5
  flutter_toggle_tab: ^1.4.1

  ##g
  google_fonts: ^6.2.1
  google_mlkit_text_recognition: ^0.6.0
  grouped_list: ^5.1.2

  ##h
  hexcolor: ^3.0.1
  horizontal_calendar: ^1.1.2
  horizontal_card_pager: ^1.1.1
  horizontal_picker: ^1.2.0
  html: ^0.15.4
  html2md: ^1.3.1
  hsv_color_pickers: ^0.3.0
  hive: ^2.2.3

  ##l
  #  latlong: ^0.6.1
  #  latlong2: ^0.8.1
  local_auth: ^1.1.11 #migate later
  logger: ^2.2.0
  lazy_load_scrollview: ^1.3.0
  like_button: ^2.0.5
#  liquid_progress_indicator: ^0.4.0
  live_background: ^0.1.3
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.0

  ##m
  mask_text_input_formatter: ^2.9.0
  mobile_scanner: ^4.0.1
#  modal_bottom_sheet: ^3.0.0
  modal_bottom_sheet:
    git:
      url: https://github.com/eli1stark/modal_bottom_sheet.git
      ref: 2b3f9f84f46418c1b337968c88883995f65f47e7
      path: modal_bottom_sheet
  multi_image_picker_view: ^0.0.17

  #https://pub.dev/packages/nav
  nav: ^1.4.2
  network_info_plus: ^5.0.3
  #https://pub.dev/packages/numberpicker
  numberpicker: ^2.1.2

  #https://pub.dev/packages/o_color_picker
  o_color_picker: ^1.0.2
  #https://pub.dev/packages/octo_image
  octo_image: ^2.0.0
  #https://pub.dev/packages/one_target_mobile_sdk
#  one_target_mobile_sdk: ^0.0.28
  #https://pub.dev/packages/overflow_view
  overflow_view: ^0.3.1
  #https://pub.dev/packages/otp_text_field
  otp_text_field: ^1.1.3

  #https://pub.dev/packages/time_planner
#  time_planner: ^0.1.1
  #https://pub.dev/packages/transparent_image
  transparent_image: ^2.0.1

  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.1

  ##q
  #https://pub.dev/packages/qr_code_scanner
  qr_code_scanner: ^1.0.1
  #https://pub.dev/packages/qr_flutter
  qr_flutter: ^4.1.0

  ##s
  #https://pub.dev/packages/scaffold_gradient_background
  #scaffold_gradient_background: ^1.0.3+1
  #https://pub.dev/packages/scrollable_positioned_list
  scrollable_positioned_list: ^0.3.8
  share_plus: ^8.0.3
  #https://pub.dev/packages/simple_url_preview
#  simple_url_preview: ^3.0.1
  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.2
  #https://pub.dev/packages/shimmer
  shimmer: ^2.0.0
  #https://pub.dev/packages/slide_countdown
  slide_countdown: ^0.6.0
  #https://pub.dev/packages/sqflite
  sqflite: ^2.3.0
  #https://pub.dev/packages/splash
  splash: ^1.1.0
  #https://pub.dev/packages/step_progress_indicator
  step_progress_indicator: ^1.0.2

  ##m
  #https://pub.dev/packages/marquee
  marquee: ^2.2.3

  ##g
  #https://pub.dev/packages/get
  get: ^4.6.6

  ##r
  #https://pub.dev/packages/random_string
  random_string: ^2.3.1
  #https://pub.dev/packages/rating_dialog
  rating_dialog: ^2.0.4
  #https://pub.dev/packages/recase
  recase: ^4.1.0
  #https://pub.dev/packages/remove_emoji
  remove_emoji: ^0.0.10
  #https://pub.dev/packages/restart_app
  restart_app: ^1.2.1
  #https://pub.dev/packages/retry
#  retry: ^3.1.2
  #https://pub.dev/packages/rxdart
  rxdart: ^0.27.7

  ##i
  #https://pub.dev/packages/infinite_scroll_pagination
  infinite_scroll_pagination: ^4.0.0
  #https://pub.dev/packages/image_gallery_saver
  image_gallery_saver: ^2.0.3
  #https://pub.dev/packages/image_picker
  image_picker: ^0.8.7
  #https://pub.dev/packages/in_app_review
  in_app_review: ^2.0.8
  #https://pub.dev/packages/intl
  intl: ^0.18.1
  #https://pub.dev/packages/internet_connection_checker
  internet_connection_checker: ^1.0.0+1
  #https://pub.dev/packages/internet_file
  internet_file: ^1.2.0

  ##h
  #https://pub.dev/packages/horizontal_data_table
  horizontal_data_table: ^4.3.1
  #https://pub.dev/packages/http
  http: ^1.1.0

  #https://pub.dev/packages/kenburns_nullsafety
  kenburns_nullsafety: ^1.0.1

  #https://pub.dev/packages/video_player
  video_player: ^2.8.1

  package_info_plus: ^7.0.0
  #https://pub.dev/packages/panara_dialogs
  panara_dialogs: ^0.1.4
  #https://pub.dev/packages/path_provider
  path_provider: ^2.1.1
  #https://pub.dev/packages/pdf_text
  pdf_text: ^0.5.0
  #https://pub.dev/packages/percent_indicator
  percent_indicator: ^4.2.3
  #https://pub.dev/packages/permission_handler
  permission_handler: ^11.0.1
  #https://pub.dev/packages/photo_view
  photo_view: ^0.14.0
  #https://pub.dev/packages/platform_device_id
  platform_device_id: ^1.0.1
  #https://pub.dev/packages/pin_code_fields
  pin_code_fields: ^8.0.1
  #https://pub.dev/packages/pip_view
  pip_view: ^0.9.7
  #https://pub.dev/packages/progress_indicators
  progress_indicators: ^1.0.0
  #https://pub.dev/packages/progress_state_button
  progress_state_button: ^1.0.4
  #https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  #https://pub.dev/packages/pretty_qr_code
  pretty_qr_code: ^2.0.2 #migrate later

  ##s
  #https://pub.dev/packages/screenshot
#  screenshot: ^2.1.0
  #https://pub.dev/packages/scrollable_table_view
  scrollable_table_view: ^1.0.1
  #https://pub.dev/packages/scroll_to_index
  scroll_to_index: ^3.0.1
  #https://pub.dev/packages/scribble
  scribble: ^0.9.1
  #https://pub.dev/packages/shape_of_view_null_safe
  shape_of_view_null_safe: ^2.0.0
  #https://pub.dev/packages/smooth_page_indicator
  smooth_page_indicator: ^1.1.0
  #https://pub.dev/packages/sidebarx
  sidebarx: ^0.16.2
  #https://pub.dev/packages/skeleton_loader
  skeleton_loader: ^2.0.0+4
  #https://pub.dev/packages/sliding_up_panel
  sliding_up_panel: ^2.0.0+1
  #https://pub.dev/packages/sticky_headers
  sticky_headers: ^0.3.0+2
  #https://pub.dev/packages/string_validator
  string_validator: ^1.0.2
  #https://pub.dev/packages/super_circle
  super_circle: ^1.0.0
  #https://pub.dev/packages/swipe_cards
  swipe_cards: ^2.0.0+1
  #https://pub.dev/packages/syncfusion_flutter_gauges
  syncfusion_flutter_gauges: ^23.1.44

  #https://pub.dev/packages/tiengviet
  tiengviet: ^1.0.0
  #https://pub.dev/packages/timeago
  timeago: ^3.6.0
  #https://pub.dev/packages/timelines
  timelines: ^0.1.0
  #https://pub.dev/packages/toggle_switch
  toggle_switch: ^2.1.0

  #https://pub.dev/packages/uuid
  uuid: ^4.3.3

  #https://pub.dev/packages/velocity_x
  velocity_x: ^4.1.1
  #https://pub.dev/packages/vertical_card_pager
  vertical_card_pager: ^1.5.0
  #https://pub.dev/packages/vibration
  vibration: ^1.8.3

  #https://pub.dev/packages/wakelock
#  wakelock: ^0.6.2
  wakelock_plus: ^1.2.4
  #https://pub.dev/packages/wave
  wave: ^0.2.2
  #https://pub.dev/packages/webview_flutter
  webview_flutter: ^3.0.4 #migate later
  #https://pub.dev/packages/web_scraper
  web_scraper: ^0.1.4
  #https://pub.dev/packages/wechat_camera_picker
  wechat_camera_picker: ^4.0.2

  ##y
  youtube_player_flutter: ^9.0.1

  ##t
  #https://pub.dev/packages/tdk_bouncingwidget
  tdk_bouncingwidget: ^1.0.4
  tiledjsonreader: ^1.3.3
  #https://pub.dev/packages/tiktoklikescroller
  tiktoklikescroller: ^0.2.5
  #https://pub.dev/packages/tuple
#  tuple: ^2.0.2
  #https://pub.dev/packages/translator
  translator: ^0.1.7

  ##p
  pdfx: ^2.6.0
#  pdfx:
#    git:
#      url: 'https://github.com/ScerIO/packages.flutter'
#      ref: '4be9de9ffed5398fd7d5f44bbb07dcd3d3f1711b'
#      path: packages/pdfx
  photo_manager: ^3.0.0

dependency_overrides:
  intl: ^0.18.1
  network_info_plus: ^5.0.3
  simple_animations: ^5.0.2
  http: ^1.1.0
#  built_value: 8.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1

  #https://pub.dev/packages/flutter_app_name
#  flutter_app_name: ^0.1.1

#  qr: ^2.0.0
#  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/coding.png"
#  flutter pub run flutter_launcher_icons:main

#flutter_app_name:
#  name: "Flutter tutorials"

flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: data_repo/fonts/Pacifico-Regular.ttf
          weight: 400

  assets:
    - assets/files/
    - assets/videos/
    - assets/images/
    - assets/pdf/
    - assets/sample/
    - assets/lottie/
    - data_repo/starwars_data.json
    - sound/slow_spring_board.mp3
    - assets/rayworld_collision_map.json
