name: hello_word
description: A new Flutter project.
publish_to: 'none'
version: 1.0.10+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  advance_pdf_viewer: ^2.0.1 #https://pub.dev/packages/advance_pdf_viewer
  animated_background: ^2.0.0 #https://pub.dev/packages/animated_background
  animated_text_kit: ^4.2.1 #https://pub.dev/packages/animated_text_kit
  avatar_glow: ^2.0.2 #https://pub.dev/packages/avatar_glow

  battery_plus: ^2.1.1 #https://pub.dev/packages/battery_plus
  basic_utils: ^4.2.0 #https://pub.dev/packages/basic_utils
  blur: ^3.0.0 #https://pub.dev/packages/blur

  cached_network_image: ^3.2.0 #https://pub.dev/packages/cached_network_image
  connectivity_plus: ^2.2.0 #https://pub.dev/packages/connectivity_plus
  country_picker: ^2.0.11 #https://pub.dev/packages/country_picker
  cupertino_icons: ^1.0.4 #https://pub.dev/packages/cupertino_icons
  crypto: ^3.0.1 #https://pub.dev/packages/crypto/install

  drag_select_grid_view: ^0.5.1 #https://pub.dev/packages/drag_select_grid_view
  device_info_plus: ^3.2.1 #https://pub.dev/packages/device_info_plus
  delayed_display: ^2.0.0 #https://pub.dev/packages/delayed_display
  dio: ^4.0.4 #https://pub.dev/packages/dio
  dotted_border: ^2.0.0 #https://pub.dev/packages/dotted_border
  draggable_scrollbar: ^0.1.0 #https://pub.dev/packages/draggable_scrollbar

  easy_debounce: ^2.0.2+1 #https://pub.dev/packages/easy_debounce
  encrypt: ^5.0.1 #https://pub.dev/packages/encrypt
  english_words: ^4.0.0 #https://pub.dev/packages/english_words
  event_bus: ^2.0.0 #https://pub.dev/packages/event_bus

  focus_detector: ^2.0.1 #https://pub.dev/packages/focus_detector
  fl_chart: ^0.45.0 #https://pub.dev/packages/fl_chart
  flutter_easyloading: ^3.0.3 #https://pub.dev/packages/flutter_easyloading
  flutter_local_notifications: ^9.3.2 #https://pub.dev/packages/flutter_local_notifications
  flutter_native_timezone: ^2.0.0 #https://pub.dev/packages/flutter_native_timezone
  flutter_native_splash: ^2.0.4 #https://pub.dev/packages/flutter_native_splash
  flutter_reaction_button: ^1.0.8 #https://pub.dev/packages/flutter_reaction_button
  flutter_slidable: ^0.6.0 #https://pub.dev/packages/flutter_slidable
  flutter_staggered_grid_view: ^0.4.0 #https://pub.dev/packages/flutter_staggered_grid_view
  flutter_svg: ^1.0.3 #https://pub.dev/packages/flutter_svg
  flutter_speed_dial: ^5.0.0+1 #https://pub.dev/packages/flutter_speed_dial
  flutter_sticky_header: ^0.6.0 #https://pub.dev/packages/flutter_sticky_header
  flutter_screen_lock: ^5.0.5 #https://pub.dev/packages/flutter_screen_lock

  horizontal_card_pager: ^1.1.1 #https://pub.dev/packages/horizontal_card_pager
  html2md: ^1.2.5 #https://pub.dev/packages/html2md

  local_auth: ^1.1.11 #https://pub.dev/packages/local_auth
  logger: ^1.1.0 #https://pub.dev/packages/logger
  lazy_load_scrollview: ^1.3.0 #https://pub.dev/packages/lazy_load_scrollview
  like_button: ^2.0.4 #https://pub.dev/packages/like_button
  lottie: ^1.2.2 #https://pub.dev/packages/lottie

  modal_bottom_sheet: ^2.0.0 #https://pub.dev/packages/modal_bottom_sheet

  network_info_plus: ^2.1.2 #https://pub.dev/packages/network_info_plus

  overflow_view: ^0.3.1 #https://pub.dev/packages/overflow_view

  transparent_image: ^2.0.0 #https://pub.dev/packages/transparent_image

  url_launcher: ^6.0.20 #https://pub.dev/packages/url_launcher

  share_plus: ^3.0.5 #https://pub.dev/packages/share_plus
  simple_url_preview: ^3.0.1 #https://pub.dev/packages/simple_url_preview
  shared_preferences: ^2.0.13 #https://pub.dev/packages/shared_preferences
  shimmer: ^2.0.0 #https://pub.dev/packages/shimmer
  sqflite: ^2.0.2 #https://pub.dev/packages/sqflite

  marquee: ^2.2.1 #https://pub.dev/packages/marquee

  get: ^4.6.1 #https://pub.dev/packages/get

  restart_app: ^1.1.0 #https://pub.dev/packages/restart_app
  rxdart: ^0.27.3 #https://pub.dev/packages/rxdart

  image_gallery_saver: ^1.7.1 #https://pub.dev/packages/image_gallery_saver
  image_picker: ^0.8.1+1 #https://pub.dev/packages/image_picker
  in_app_review: ^2.0.2 #https://pub.dev/packages/in_app_review
  intl: ^0.17.0 #https://pub.dev/packages/intl

  horizontal_data_table: ^3.3.0 #https://pub.dev/packages/horizontal_data_table
  http: ^0.13.3 #https://pub.dev/packages/http

  video_player: ^2.1.5 #https://pub.dev/packages/video_player

  package_info_plus: ^1.0.2 #https://pub.dev/packages/package_info_plus
  path_provider: ^2.0.3 #https://pub.dev/packages/path_provider
  permission_handler: ^9.0.1 #https://pub.dev/packages/permission_handler
  photo_view: ^0.12.0 #https://pub.dev/packages/photo_view
  pin_code_fields: ^7.2.0 #https://pub.dev/packages/pin_code_fields
  progress_state_button: ^1.0.3 #https://pub.dev/packages/progress_state_button
  pull_to_refresh: ^2.0.0 #https://pub.dev/packages/pull_to_refresh

  tiengviet: ^0.5.0 #https://pub.dev/packages/tiengviet
  timeago: ^3.1.0 #https://pub.dev/packages/timeago

  wakelock: ^0.5.6 #https://pub.dev/packages/wakelock
  wave: ^0.2.0 #https://pub.dev/packages/wave
  webview_flutter: ^2.0.6 #https://pub.dev/packages/webview_flutter
  web_scraper: ^0.1.4 #https://pub.dev/packages/web_scraper

  #none null safety
  #flutter_swiper: ^1.1.6 #https://pub.dev/packages/flutter_swiper
  #md2_tab_indicator: ^1.0.2 #https://pub.dev/packages/md2_tab_indicator
  #drag_to_expand: ^0.0.1 #https://pub.dev/packages/drag_to_expand
  #kenburns: ^1.0.5 #https://pub.dev/packages/kenburns

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2" #https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_l.png"
#  flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: data_repo/fonts/Pacifico-Regular.ttf
          weight: 400

  assets:
    #    - assets/
    - assets/videos/
    - assets/images/
    - assets/pdf/
    - assets/sample/
    - assets/lottie/
    - data_repo/starwars_data.json
    - sound/slow_spring_board.mp3
